# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


A1:list(a)的做法是每一列的數值印下來，每一行array還是有各自的參數，tolist()的做法是一列列的數值統整成一條list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [3]:
# 記得先 Import 正確的套件
import random

In [4]:
a = np.random.randint(10, size=6) 
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('data: ', a.data)


ndim:  1
shape:  (6,)
size:  6
dtype:  int64
itemsize:  8
data:  <memory at 0x7ff22ea4d1c0>


In [7]:
b = np.random.randint(10, size=(3,4)) 

print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('data: ', b.data)


ndim:  2
shape:  (3, 4)
size:  12
dtype:  int64
itemsize:  8
data:  <memory at 0x7ff22eebfa00>


In [8]:
c = np.random.randint(10, size=(2,3,2)) 

print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('data: ', c.data)


ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int64
itemsize:  8
data:  <memory at 0x7ff22f06a130>


A2:
在A陣列中，A是一維陣列，第一個維度的大小是6，陣列中有6個元素，資料型態為整數，佔的空間只有8 bits, 儲存在0x7ff22ea4d1c0這個位置
在B陣列中，B是二維陣列，第一個維度的大小是3，第二個維度是4，陣列中有12個元素，資料型態為整數，佔的空間只有8 bits, 儲存在0x7ff22eebfa00這個位置
在C陣列中，C是三維陣列，第一個維度的大小是2，第二個維度的大小是3，第三個維度的大小是2，陣列中有12個元素，資料型態為整數，佔的空間只有8 bits, 儲存在0x7ff22f06a130這個位置


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
def tolist(iterable):
    if 
    

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
